// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP_XCteI1gqz8TqZfmsO7xSsGMCfI_WGM',
    appId: '1:594350363593:web:c114c382b1d3cf812bce18',
    messagingSenderId: '594350363593',
    projectId: 'chatapplication-12b4a',
    authDomain: 'chatapplication-12b4a.firebaseapp.com',
    storageBucket: 'chatapplication-12b4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzCCym4QWIn4CSpWl37_pWDRCa_RmRvc',
    appId: '1:594350363593:android:16618391a7a73d812bce18',
    messagingSenderId: '594350363593',
    projectId: 'chatapplication-12b4a',
    storageBucket: 'chatapplication-12b4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Ro2ihbs-2hQlCHFQzRW_dcD86J6GE5s',
    appId: '1:594350363593:ios:c2d2be523756ec0a2bce18',
    messagingSenderId: '594350363593',
    projectId: 'chatapplication-12b4a',
    storageBucket: 'chatapplication-12b4a.appspot.com',
    iosBundleId: 'com.mine.chatapp',
  );
}
